# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cinch-lmgtfy}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Bergoo", "Michael Archibald"]
  s.date = %q{2011-03-26}
  s.description = %q{A Cinch plugin for Let Me Google That For You!}
  s.email = %q{victor.bergoo@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "lib/cinch/plugins/lmgtfy.rb"
  ]
  s.homepage = %q{http://github.com/neener54/cinch-lmgtfy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Cinch plugin for Let Me Google That For You}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3
      s.add_runtime_dependency "cinch"
      s.add_runtime_dependency "json"
      s.add_runtime_dependency "curb"
  end
end

